### ISSUE TITLE
servicecomb-edge调用mesher代理的服务失败

### ISSUE THREAD

**Issue by xiangyanggong** [apache/servicecomb-mesher#124]
看了文档，也运行了bmi的实例，基本上理解mesher的工作原理以及使用方法，但我疑惑的是servicecomb体系所有的通信都是围绕“契约”的，如果说我现在的新系统是基于servicecomb的，所有新的微服务也是使用 java-chasis 编写，但有一个老的服务B使用的是nodejs可以直接复用，那我使用mesher将该服务集成进新的系统。
假设现在使用一个基于java-chasis开发的微服务A调用B
1.是否B需要手动编写“契约”文件呢？因为A调用B的API时会从SC拉取契约，如果没有契约的话，调用应该会失败
2.假设B需要提供契约文件，为什么我每次启动mesher（1.6.3）之后，我写的契约都会删除，然后mesher自己创建一个新的契约文件
目前测试的结果使用  request -> edge (java) -> mesher -> nodejs，edge会报错

**Comment by tianxiaoliang** [comment]
这是个bug，mesher应该屏蔽段自动契约生成的能力

**Comment by xiangyanggong** [comment]
通过验证得出：
1.如果基于java-chassis开发的微服务A需要调用异构服务B，服务B使用mesher代理，是需要提供手写的契约文件
2.关于手动编写的契约在mesher启动时会被覆盖，这个是需要在mesher的chassis.yml文件中添加配置：cse.noRefreshSchema=true（PS: 关于这个配置 go-chassis项目中有相关说明），这样的话，就不会自动生成契约了
