### ISSUE TITLE
mesher如何从配置中心读取数据

### ISSUE THREAD

**Issue by hf1154104163** [apache/servicecomb-mesher#136]
我写的servicemesh是连接了配置中心了，但如何从配置中心获取下发的配置信息呐？

![image](https://user-images.githubusercontent.com/45277511/102198782-c48aa280-3efd-11eb-92b5-6953a8fa1c37.png)

**Comment by tianxiaoliang** [comment]
https://go-chassis.readthedocs.io/en/latest/control-plane/servicecomb.html#config-servers

**Comment by hf1154104163** [comment]
> https://go-chassis.readthedocs.io/en/latest/control-plane/servicecomb.html#config-servers
额，不是go-chassis,是servicemesh微服务连接配置中心如何读取数据的

**Comment by tianxiaoliang** [comment]
> > https://go-chassis.readthedocs.io/en/latest/control-plane/servicecomb.html#config-servers
> > 额，不是go-chassis,是servicemesh微服务连接配置中心如何读取数据的

配置方式是一样的

**Comment by hf1154104163** [comment]
> > > https://go-chassis.readthedocs.io/en/latest/control-plane/servicecomb.html#config-servers
> > > 额，不是go-chassis,是servicemesh微服务连接配置中心如何读取数据的
> 
> 配置方式是一样的

我关注的不是怎么连接配置中心，而是怎么从配置中心获取数据，比如mesher代理的python项目。从那个链接中没有发现相关信息，方便加联系方式交流下不

**Comment by tianxiaoliang** [comment]
明白你的意思了，你用的哪个配置中心呢

**Comment by hf1154104163** [comment]
> 明白你的意思了，你用的哪个配置中心呢

java chasis提供的服务注册和配置中心，跟servicecomb差不多。我的需求是，由于mesher代理python项目去注册和发现服务，那么python项目又如何从配置中心获取下发的数据，

**Comment by tianxiaoliang** [comment]
> > 明白你的意思了，你用的哪个配置中心呢
> 
> java chasis提供的服务注册和配置中心，跟servicecomb差不多。我的需求是，由于mesher代理python项目去注册和发现服务，那么python项目又如何从配置中心获取下发的数据，

只能自己实现restful API client，这个问题其实很多人都在问，可以贡献给社区最好

**Comment by hf1154104163** [comment]
> > > 明白你的意思了，你用的哪个配置中心呢
> > 
> > 
> > java chasis提供的服务注册和配置中心，跟servicecomb差不多。我的需求是，由于mesher代理python项目去注册和发现服务，那么python项目又如何从配置中心获取下发的数据，
> 
> 只能自己实现restful API client，这个问题其实很多人都在问，可以贡献给社区最好

是的，我看了一些文档都只是说连接配置中心，但没有给出具体的代码，从配置中心获取所需的数据，这个确实挺费解的，除非项目代码中直接发送请求给配置中心，但这又跟微服务没啥关系了

**Comment by tianxiaoliang** [comment]
https://github.com/apache/servicecomb-kie 社区提供的配置中心是这个，我也推荐你自建和使用。你说的配置中心可能是华为云提供的商业版，不该在社区讨论。

**Comment by hf1154104163** [comment]
servicemesh调用对方服务，对方服务只能是小写字母，比如obpservice。假如对方服务名是OBPservice, 我这边就会报找不到服务的错误，请问如何解决？
