### ISSUE TITLE
采用容器部署的方式，一个pod，两个容器,业务容器还没启动成功，mesher容器已经启动成功，已经注册到service-center.

### ISSUE THREAD

**Issue by chenchanglong1997** [apache/servicecomb-mesher#145]
有什么机制可以规避这种问题。

**Comment by tianxiaoliang** [comment]
https://mesher.readthedocs.io/en/latest/configurations/health.html  可以先通过搜索文档关键字来自行找方案

**Comment by tianxiaoliang** [comment]
另外，欢迎针对该功能提供更多的问题，主动贡献社区，如果可以贡献文档和代码，那就非常好了，感谢

**Comment by zaizailong** [comment]
> 有什么机制可以规避这种问题。

请问下，这个问题已经解决了么？ issues里好像并没有说怎么解决该问题

**Comment by tianxiaoliang** [comment]
就在文档链接里

**Comment by tianxiaoliang** [comment]
@chenchanglong1997 如果这位朋友还有疑问，可否给他更进一步的提示

**Comment by chenchanglong1997** [comment]
> > 有什么机制可以规避这种问题。
> 
> 请问下，这个问题已经解决了么？ issues里好像并没有说怎么解决该问题

可以从容器部署那块着手，容器的启停顺序https://xie.infoq.cn/article/22a084f0fb95b3e7cf01a85b9
