### ISSUE TITLE
go build Mesher error when add zipkin tracing 

### ISSUE THREAD

**Issue by hzyzhd** [apache/servicecomb-mesher#66]
i add zipkin tracer by :
1、Import _ "github.com/go-chassis/go-chassis-plugins/tracing/zipkin" in mesher.go.
2、Add  chassisHandler.TracingConsumer for consumerChain in file bootstrap.go.
3、Add chassisHandler.TracingProvider for providerChain in file bootstrap.go.
then go build mesher.go,  and get an error: 
go/pkg/mod/github.com/go-chassis/go-chassis-plugins@v0.0.0-20190507123504-83783d9c730e/tracing/zipkin/zipkin.go:75:3: undefined: zipkintracer.WithPrefixTracerState

**Comment by surechen** [comment]
Please try execute the command to configure the environment:
In linux: export GOPROXY=https://goproxy.io
In windows PowerShell: $env:GOPROXY=https://goproxy.io

**Comment by hzyzhd** [comment]
Thanks，but I  get the same error: go-chassis-plugins@v0.0.0-20190507123504-83783d9c730e/tracing/zipkin/zipkin.go:75:3: undefined: zipkintracer.WithPrefixTracerState.

**Comment by surechen** [comment]
Please try adding this  in go.mod replace:github.com/openzipkin-contrib/zipkin-go-opentracing v0.3.5 => github.com/go-chassis/zipkin-go-opentracing v0.3.5-0.20190321072447-42cf74fc2a92
