### ISSUE TITLE
File suffixes in docs inconsistent 

### ISSUE THREAD

**Issue by AngLi2** [apache/servicecomb-mesher#87]
File suffixes in docs are inconsistent. Some are markdown format while others are rst fomat. It is ok for user to read and study from mesher docs but not convenient for contributers to optimzie docs. Shall we normalized the formats?

**Comment by tianxiaoliang** [comment]
rst是为了写出一些md写不出来的功能的，但是仍然有些人不希望学习rst，而使用自己熟练的工具编写文档，还是不做限制了，rst md皆可

**Comment by AngLi2** [comment]
Got it, thx. I will study and use rst.

**Comment by tianxiaoliang** [comment]
嗯 rst功能强大，不过当前我没有找到一种方法能自己搭建出像托管rtd那样的文档生成方法，比如有版本管理，i8n
